In [0]:
df = spark.read\
    .options(delimiter=";", inferSchema= True, header=True,encoding = "latin1", badRecordsPath = "/tmp/badRecords")\
    .format("csv")\
    .load("dbfs:/FileStore/shared_uploads/carlos.ramosp@pucp.edu.pe/casos_fem.csv")

In [0]:
original_names = ['AÑO',
'PERIODO',
'FECHA ENVIO',
'CODIGO ENTIDAD',
'ENTIDAD',
'CODIGO LINEA',
'LINEA INTERVENCION',
'CODIGO SERVICIO',
'NOMBRE SERVICIO',
'UBIGEO',
'DEPARTAMENTO',
'PROVINCIA',
'DISTRITO',
'CODIGO CENTRO ATENCION',
'NOMBRE CENTRO ATENCION',
'N° DE CEM',
'N° CASOS ATENDIDOS-TOTAL',
'N° CASOS ATENDIDOS - HOMBRES - TOTAL',
'N° CASOS ATENDIDOS - MUJERES - TOTAL',
'N° CASOS ATENDIDOS - VIOLENCIA PSICOLOGICA',
'N° CASOS ATENDIDOS - VIOLENCIA FISICA',
'N° CASOS ATENDIDOS - VIOLENCIA SEXUAL',
'N° CASOS ATENDIDOS - VIOLENCIA ECONÓMICA O PATRIMONIAL',
'N° CASOS ATENDIDOS - 0_5 - TOTAL',
'N° CASOS ATENDIDOS - 0_5 - HOMBRES',
'N° CASOS ATENDIDOS - 0_5 - MUJERES',
'N° CASOS ATENDIDOS - 6_11 - TOTAL',
'N° CASOS ATENDIDOS - 6_11 - HOMBRES',
'N° CASOS ATENDIDOS - 6_11 - MUJERES',
'N° CASOS ATENDIDOS - 12_17 - TOTAL',
'N° CASOS ATENDIDOS - 12_17 - HOMBRES',
'N° CASOS ATENDIDOS - 12_17 - MUJERES',
'N° CASOS ATENDIDOS - 18_25 - TOTAL',
'N° CASOS ATENDIDOS - 18_25  - HOMBRES',
'N° CASOS ATENDIDOS - 18_25 - MUJERES',
'N° CASOS ATENDIDOS - 18_29 - TOTAL',
'N° CASOS ATENDIDOS - 18_29  - HOMBRES',
'N° CASOS ATENDIDOS - 18_29 - MUJERES',
'N° CASOS ATENDIDOS - 26_35 - TOTAL',
'N° CASOS ATENDIDOS - 26_35 - HOMBRES',
'N° CASOS ATENDIDOS - 26_35 - MUJERES',
'N° CASOS ATENDIDOS - 36_45 - TOTAL',
'N° CASOS ATENDIDOS - 36_45 - HOMBRES',
'N° CASOS ATENDIDOS - 36_45 - MUJERES',
'N° CASOS ATENDIDOS - 30_59 - TOTAL',
'N° CASOS ATENDIDOS - 30_59 - HOMBRES',
'N° CASOS ATENDIDOS - 30_59 - MUJERES',
'N° CASOS ATENDIDOS - 46_59 - TOTAL',
'N° CASOS ATENDIDOS - 46_59 - HOMBRES',
'N° CASOS ATENDIDOS - 46_59 - MUJERES',
'N° CASOS ATENDIDOS - 60_MÁS - TOTAL',
'N° CASOS ATENDIDOS - 60_MÁS - HOMBRES',
'N° CASOS ATENDIDOS - 60_MÁS - MUJERES',
'N° DE ACTIVIDADES - TOTAL'
]

In [0]:
df = df.toDF(*original_names)

In [0]:
columns_to_drop = ["CODIGO ENTIDAD", "ENTIDAD", "CODIGO LINEA","LINEA INTERVENCION","CODIGO SERVICIO","NOMBRE SERVICIO","N° DE CEM"]
df = df.drop(*columns_to_drop)

In [0]:
columns_to_clean = [
    'N° CASOS ATENDIDOS-TOTAL',
    'N° CASOS ATENDIDOS - HOMBRES - TOTAL',
    'N° CASOS ATENDIDOS - MUJERES - TOTAL',
    'N° CASOS ATENDIDOS - VIOLENCIA PSICOLOGICA',
    'N° CASOS ATENDIDOS - VIOLENCIA FISICA',
    'N° CASOS ATENDIDOS - VIOLENCIA SEXUAL',
    'N° CASOS ATENDIDOS - VIOLENCIA ECONÓMICA O PATRIMONIAL',
    'N° CASOS ATENDIDOS - 0_5 - TOTAL',
    'N° CASOS ATENDIDOS - 0_5 - HOMBRES',
    'N° CASOS ATENDIDOS - 0_5 - MUJERES',
    'N° CASOS ATENDIDOS - 6_11 - TOTAL',
    'N° CASOS ATENDIDOS - 6_11 - HOMBRES',
    'N° CASOS ATENDIDOS - 6_11 - MUJERES',
    'N° CASOS ATENDIDOS - 12_17 - TOTAL',
    'N° CASOS ATENDIDOS - 12_17 - HOMBRES',
    'N° CASOS ATENDIDOS - 12_17 - MUJERES',
    'N° CASOS ATENDIDOS - 18_25 - TOTAL',
    'N° CASOS ATENDIDOS - 18_25  - HOMBRES',
    'N° CASOS ATENDIDOS - 18_25 - MUJERES',
    'N° CASOS ATENDIDOS - 18_29 - TOTAL',
    'N° CASOS ATENDIDOS - 18_29  - HOMBRES',
    'N° CASOS ATENDIDOS - 18_29 - MUJERES',
    'N° CASOS ATENDIDOS - 26_35 - TOTAL',
    'N° CASOS ATENDIDOS - 26_35 - HOMBRES',
    'N° CASOS ATENDIDOS - 26_35 - MUJERES',
    'N° CASOS ATENDIDOS - 36_45 - TOTAL',
    'N° CASOS ATENDIDOS - 36_45 - HOMBRES',
    'N° CASOS ATENDIDOS - 36_45 - MUJERES',
    'N° CASOS ATENDIDOS - 30_59 - TOTAL',
    'N° CASOS ATENDIDOS - 30_59 - HOMBRES',
    'N° CASOS ATENDIDOS - 30_59 - MUJERES',
    'N° CASOS ATENDIDOS - 46_59 - TOTAL',
    'N° CASOS ATENDIDOS - 46_59 - HOMBRES',
    'N° CASOS ATENDIDOS - 46_59 - MUJERES',
    'N° CASOS ATENDIDOS - 60_MÁS - TOTAL',
    'N° CASOS ATENDIDOS - 60_MÁS - HOMBRES',
    'N° CASOS ATENDIDOS - 60_MÁS - MUJERES',
    'N° DE ACTIVIDADES - TOTAL'
]

In [0]:
from pyspark.sql.functions import regexp_replace, trim, col

for column in columns_to_clean:
    df = df.withColumn(
        column,
        regexp_replace(trim(col(column)), ",", "").cast("int")
    )

In [0]:
new_columns = [(col_name.replace("Ñ", "NH")).replace("N°","NUM") for col_name in df.columns]

# Rename the DataFrame with updated column names
df = df.toDF(*new_columns)

In [0]:
from pyspark.sql.types import StringType, StructType, IntegerType, DateType, DoubleType,StructField
schema = StructType([
    StructField("ANHO",IntegerType(), True),
    StructField("PERIODO",StringType(), True),
    StructField("FECHA ENVIO",DateType(), True),
    StructField("UBIGEO",IntegerType(), True),
    StructField("DEPARTAMENTO",StringType(), True),
    StructField("PROVINCIA",StringType(), True),
    StructField("DISTRITO",StringType(), True),
    StructField("CODIGO CENTRO ATENCION",StringType(), True),
    StructField("NOMBRE CENTRO ATENCION",StringType(), True),
    StructField("NUM CASOS ATENDIDOS-TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - HOMBRES - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - MUJERES - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - VIOLENCIA PSICOLOGICA",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - VIOLENCIA FISICA",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - VIOLENCIA SEXUAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - VIOLENCIA ECONÓMICA O PATRIMONIAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 0_5 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 0_5 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 0_5 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 6_11 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 6_11 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 6_11 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 12_17 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 12_17 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 12_17 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 18_25 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 18_25 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 18_25 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 18_29 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 18_29 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 18_29 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 26_35 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 26_35 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 26_35 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 36_45 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 36_45 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 36_45 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 30_59 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 30_59 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 30_59 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 46_59 - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 46_59 - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 46_59 - MUJERES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 60_MÁS - TOTAL",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 60_MÁS - HOMBRES",IntegerType(), True),
    StructField("NUM CASOS ATENDIDOS - 60_MÁS - MUJERES",IntegerType(), True),
    StructField("NUM DE ACTIVIDADES - TOTAL",IntegerType(), True)
])

In [0]:
df = spark.createDataFrame(df.rdd, schema)

In [0]:
###

from pyspark.sql.functions import col

# Assuming df is your Spark DataFrame

# Step 1: Get all string columns
string_cols = [field.name for field in df.schema.fields if isinstance(field.dataType, StringType)]

# Step 2: For each string column, get the distinct values
for column in string_cols:
    print(f"Unique values for column '{column}':")
    df.select(column).distinct().show()

Unique values for column 'PERIODO':
+---------+
|  PERIODO|
+---------+
|ENE - OCT|
|ENE - DIC|
+---------+

Unique values for column 'DEPARTAMENTO':
+---------------+
|   DEPARTAMENTO|
+---------------+
|       AYACUCHO|
|          JUNÍN|
|         CALLAO|
|    LA LIBERTAD|
|        HUÁNUCO|
|       AMAZONAS|
|       AREQUIPA|
|           PUNO|
|     LAMBAYEQUE|
|  MADRE DE DIOS|
|          PIURA|
|   HUANCAVELICA|
|         LORETO|
|      CAJAMARCA|
|       MOQUEGUA|
|          CUSCO|
|         ÁNCASH|
|       APURÍMAC|
|            ICA|
|LIMA PROVINCIAS|
+---------------+
only showing top 20 rows

Unique values for column 'PROVINCIA':
+-----------+
|  PROVINCIA|
+-----------+
|     CAMANÁ|
|   HUANCAYO|
|    AYABACA|
|     CALLAO|
|       AMBO|
|      SANTA|
|    ABANCAY|
|CHANCHAMAYO|
| CHINCHEROS|
|   AREQUIPA|
|     CAÑETE|
|   ACOBAMBA|
|   HUAMANGA|
|CHACHAPOYAS|
|  CAJAMARCA|
|  ANTABAMBA|
|      BAGUA|
|   CHICLAYO|
|ANDAHUAYLAS|
|       LIMA|
+-----------+
only showing top 20 rows

Unique values for column 'DISTRITO':
+-----------+
|   DISTRITO|
+-----------+
|   AYACUCHO|
|     CAMANÁ|
|    AYABACA|
|     CALLAO|
|       AMBO|
|     CHILCA|
|    ABANCAY|
|CHANCHAMAYO|
| CHINCHEROS|
|   AREQUIPA|
|   ACOBAMBA|
|CHACHAPOYAS|
|  CAJAMARCA|
|  ANTABAMBA|
|   IMPERIAL|
|      BAGUA|
|   CHICLAYO|
| CARABAYLLO|
|ANDAHUAYLAS|
|   CHIMBOTE|
+-----------+
only showing top 20 rows

Unique values for column 'CODIGO CENTRO ATENCION':
+----------------------+
|CODIGO CENTRO ATENCION|
+----------------------+
|                CEM015|
|                CEM006|
|                CEM010|
|                CEM013|
|                CEM005|
|                CEM020|
|                CEM016|
|                CEM003|
|                CEM019|
|                CEM021|
|                CEM008|
|                CEM011|
|                CEM018|
|                CEM007|
|                CEM012|
|                CEM001|
|                CEM014|
|                CEM002|
|                CEM004|
|                CEM009|
+----------------------+
only showing top 20 rows

Unique values for column 'NOMBRE CENTRO ATENCION':
+----------------------+
|NOMBRE CENTRO ATENCION|
+----------------------+
|               AYABACA|
|                CALLAO|
|                  AMBO|
|                CAMANA|
|                CHILCA|
|               ABANCAY|
|           CHANCHAMAYO|
|            CHINCHEROS|
|              AREQUIPA|
|                CAÑETE|
|              ACOBAMBA|
|              HUAMANGA|
|           CHACHAPOYAS|
|             CAJAMARCA|
|             ANTABAMBA|
|                 BAGUA|
|              CHICLAYO|
|            CARABAYLLO|
|           ANDAHUAYLAS|
|              CHIMBOTE|
+----------------------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import col, when
#We get those columns that are numeric values and have null values
name_num_list = [column for column in df.columns if column.startswith("NUM") and column != "NUM DE CEM"]

for column in name_num_list:
    df = df.withColumn(column,when(col(column).isNull(), 0).otherwise(col(column)))

In [0]:
df

In [0]:
df.limit(10).toPandas()

,ANHO,PERIODO,FECHA ENVIO,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,CODIGO CENTRO ATENCION,NOMBRE CENTRO ATENCION,NUM CASOS ATENDIDOS-TOTAL,...,NUM CASOS ATENDIDOS - 30_59 - TOTAL,NUM CASOS ATENDIDOS - 30_59 - HOMBRES,NUM CASOS ATENDIDOS - 30_59 - MUJERES,NUM CASOS ATENDIDOS - 46_59 - TOTAL,NUM CASOS ATENDIDOS - 46_59 - HOMBRES,NUM CASOS ATENDIDOS - 46_59 - MUJERES,NUM CASOS ATENDIDOS - 60_MÁS - TOTAL,NUM CASOS ATENDIDOS - 60_MÁS - HOMBRES,NUM CASOS ATENDIDOS - 60_MÁS - MUJERES,NUM DE ACTIVIDADES - TOTAL
0,2013,ENE - DIC,2014-01-05,30101,APURÍMAC,ABANCAY,ABANCAY,CEM001,ABANCAY,142,...,0,0,0,20,0,0,7,0,0,4146
1,2013,ENE - DIC,2014-01-05,90201,HUANCAVELICA,ACOBAMBA,ACOBAMBA,CEM002,ACOBAMBA,84,...,0,0,0,9,0,0,5,0,0,4595
2,2013,ENE - DIC,2014-01-05,100201,HUÁNUCO,AMBO,AMBO,CEM003,AMBO,145,...,0,0,0,16,0,0,3,0,0,8977
3,2013,ENE - DIC,2014-01-05,30201,APURÍMAC,ANDAHUAYLAS,ANDAHUAYLAS,CEM004,ANDAHUAYLAS,408,...,0,0,0,41,0,0,10,0,0,446
4,2013,ENE - DIC,2014-01-05,30301,APURÍMAC,ANTABAMBA,ANTABAMBA,CEM005,ANTABAMBA,55,...,0,0,0,9,0,0,5,0,0,1345
5,2013,ENE - DIC,2014-01-05,200201,PIURA,AYABACA,AYABACA,CEM006,AYABACA,144,...,0,0,0,13,0,0,6,0,0,1864
6,2013,ENE - DIC,2014-01-05,50101,AYACUCHO,HUAMANGA,AYACUCHO,CEM007,HUAMANGA,564,...,0,0,0,82,0,0,23,0,0,7524
7,2013,ENE - DIC,2014-01-05,10201,AMAZONAS,BAGUA,BAGUA,CEM008,BAGUA,206,...,0,0,0,10,0,0,6,0,0,6844
8,2013,ENE - DIC,2014-01-05,60101,CAJAMARCA,CAJAMARCA,CAJAMARCA,CEM009,CAJAMARCA,338,...,0,0,0,23,0,0,12,0,0,6464
9,2013,ENE - DIC,2014-01-05,70101,CALLAO,CALLAO,CALLAO,CEM010,CALLAO,277,...,0,0,0,22,0,0,6,0,0,6887

In [0]:
df.filter(col("DISTRITO") == "TACNA").toPandas()

,ANHO,PERIODO,FECHA ENVIO,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,CODIGO CENTRO ATENCION,NOMBRE CENTRO ATENCION,NUM CASOS ATENDIDOS-TOTAL,...,NUM CASOS ATENDIDOS - 30_59 - TOTAL,NUM CASOS ATENDIDOS - 30_59 - HOMBRES,NUM CASOS ATENDIDOS - 30_59 - MUJERES,NUM CASOS ATENDIDOS - 46_59 - TOTAL,NUM CASOS ATENDIDOS - 46_59 - HOMBRES,NUM CASOS ATENDIDOS - 46_59 - MUJERES,NUM CASOS ATENDIDOS - 60_MÁS - TOTAL,NUM CASOS ATENDIDOS - 60_MÁS - HOMBRES,NUM CASOS ATENDIDOS - 60_MÁS - MUJERES,NUM DE ACTIVIDADES - TOTAL
0,2013,ENE - DIC,2014-01-05,230101,TACNA,TACNA,TACNA,CEM098,TACNA,571,...,0,0,0,57,0,0,30,0,0,9628
1,2014,ENE - DIC,2015-01-10,230101,TACNA,TACNA,TACNA,CEM098,TACNA,529,...,0,0,0,62,0,0,23,0,0,7744
2,2012,ENE - DIC,2013-01-05,230101,TACNA,TACNA,TACNA,CEM098,TACNA,572,...,0,0,0,52,0,0,28,0,0,9762
3,2015,ENE - DIC,2016-01-11,230101,TACNA,TACNA,TACNA,CEM098,TACNA,455,...,0,0,0,45,0,0,15,0,0,7328
4,2016,ENE - DIC,2016-12-13,230101,TACNA,TACNA,TACNA,CEM098,TACNA,498,...,240,2,238,0,0,0,13,4,9,717
5,2017,ENE - DIC,2018-01-16,230101,TACNA,TACNA,TACNA,CEM098,TACNA,454,...,184,3,181,0,0,0,27,9,18,7425
6,2018,ENE - DIC,2019-01-15,230101,TACNA,TACNA,TACNA,CEM098,CEM TACNA,444,...,168,4,164,0,0,0,38,5,33,8025
7,2019,ENE - DIC,2020-01-14,230101,TACNA,TACNA,TACNA,CEM098,CEM TACNA,556,...,226,14,212,0,0,0,51,9,42,10627
8,2020,ENE - DIC,2021-01-15,230101,TACNA,TACNA,TACNA,CEM098,CEM TACNA,275,...,108,2,106,0,0,0,21,4,17,7008
9,2020,ENE - DIC,2021-01-15,230101,TACNA,TACNA,TACNA,COM156,CEM COMISARÍA AUGUSTO B. LEGUIA,86,...,33,1,32,0,0,0,2,0,2,2445
10,2021,ENE - DIC,2021-01-17,230101,TACNA,TACNA,TACNA,CEM098,CEM TACNA,275,...,119,6,113,0,0,0,28,2,26,12897
11,2021,ENE - DIC,2021-01-17,230101,TACNA,TACNA,TACNA,COM156,CEM COMISARÍA AUGUSTO B. LEGUIA,313,...,102,4,98,0,0,0,19,7,12,22621
12,2021,ENE - DIC,2021-01-17,230101,TACNA,TACNA,TACNA,COM179,CEM COMISARÍA LA NATIVIDAD,71,...,31,2,29,0,0,0,9,0,9,3394
13,2022,ENE - DIC,2023-03-15,230101,TACNA,TACNA,TACNA,CEM098,CEM TACNA,206,...,81,9,72,0,0,0,22,5,17,9927
14,2022,ENE - DIC,2023-03-15,230101,TACNA,TACNA,TACNA,COM156,CEM COMISARÍA AUGUSTO B. LEGUIA,361,...,155,5,150,0,0,0,14,2,12,30136
15,2022,ENE - DIC,2023-03-15,230101,TACNA,TACNA,TACNA,COM179,CEM COMISARÍA LA NATIVIDAD,274,...,100,3,97,0,0,0,19,2,17,17915
16,2023,ENE - DIC,2024-01-15,230101,TACNA,TACNA,TACNA,CEM098,CEM TACNA,274,...,95,3,92,0,0,0,27,7,20,17503
17,2023,ENE - DIC,2024-01-15,230101,TACNA,TACNA,TACNA,COM156,CEM COMISARÍA AUGUSTO B. LEGUIA,275,...,112,4,108,0,0,0,19,3,16,23732
18,2023,ENE - DIC,2024-01-15,230101,TACNA,TACNA,TACNA,COM179,CEM COMISARÍA LA NATIVIDAD,247,...,102,5,97,0,0,0,30,3,27,13481
19,2024,ENE - OCT,2024-11-15,230101,TACNA,TACNA,TACNA,CEM098,CEM TACNA,188,...,66,2,64,0,0,0,23,9,14,0
20,2024,ENE - OCT,2024-11-15,230101,TACNA,TACNA,TACNA,COM156,CEM COMISARÍA AUGUSTO B. LEGUIA,304,...,109,3,106,0,0,0,17,3,14,0
21,2024,ENE - OCT,2024-11-15,230101,TACNA,TACNA,TACNA,COM179,CEM COMISARÍA LA NATIVIDAD,277,...,126,8,118,0,0,0,24,2,22,0

In [0]:
df.write.mode("overwrite").parquet("dbfs:/FileStore/data_cleaned.parquet")

In [0]:
display(df)

In [0]:
df.dtypes

Out[151]: [('ANHO', 'int'),
 ('PERIODO', 'string'),
 ('FECHA ENVIO', 'date'),
 ('UBIGEO', 'int'),
 ('DEPARTAMENTO', 'string'),
 ('PROVINCIA', 'string'),
 ('DISTRITO', 'string'),
 ('CODIGO CENTRO ATENCION', 'string'),
 ('NOMBRE CENTRO ATENCION', 'string'),
 ('NUM CASOS ATENDIDOS-TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - HOMBRES - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - MUJERES - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - VIOLENCIA PSICOLOGICA', 'int'),
 ('NUM CASOS ATENDIDOS - VIOLENCIA FISICA', 'int'),
 ('NUM CASOS ATENDIDOS - VIOLENCIA SEXUAL', 'int'),
 ('NUM CASOS ATENDIDOS - VIOLENCIA ECONÓMICA O PATRIMONIAL', 'int'),
 ('NUM CASOS ATENDIDOS - 0_5 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 0_5 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 0_5 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 6_11 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 6_11 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 6_11 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 12_17 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 12_17 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 12_17 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 18_25 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 18_25 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 18_25 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 18_29 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 18_29 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 18_29 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 26_35 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 26_35 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 26_35 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 36_45 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 36_45 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 36_45 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 30_59 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 30_59 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 30_59 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 46_59 - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 46_59 - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 46_59 - MUJERES', 'int'),
 ('NUM CASOS ATENDIDOS - 60_MÁS - TOTAL', 'int'),
 ('NUM CASOS ATENDIDOS - 60_MÁS - HOMBRES', 'int'),
 ('NUM CASOS ATENDIDOS - 60_MÁS - MUJERES', 'int'),
 ('NUM DE ACTIVIDADES - TOTAL', 'int')]